# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e3e6c90e8b8d580cf0a4bc954cf2c9a9cc0cde0c9dc4a1241b344ad13ff69189b40cf614148eb0b0674a1c619bfb21d3ea2e06102d8da4c9ca6ea9d83c04db3

test:
  secret_key_base: 1a6b83a49219ea028354c5b4dbf2dd8643e249eb85981db4f75467ad471984551dbab093e09d14a629b9bcb7846cd772df3b6495d63713f9e8d47e93acca31eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
